[tool.poetry]
name = "templyte"
version = "0.1.0"
description = "Python Boilerplate Project"
authors = ["Juan Manso <juanmanso@gmail.com>"]
license = "GNU GPLv3"
readme = "README.md"
homepage = "https://github.com/juanmanso/templyte"
repository = "https://github.com/juanmanso/templyte"
keywords = ["template", "python", "templyte"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
