name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - develop
      - release
  workflow_dispatch:

jobs:
  lint_and_test:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: ['3.7', '3.8']

    name: Python ${{ matrix.python-version }}
    steps:
    - name: Checkout repostiory
      uses: actions/checkout@v2

    - name: Install python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install dependencies
      run: pip install nox==2020.12.31 poetry==1.1.4

    - name: Run linter and tests suites
      run: nox
