name: Code Coverage

on:
  push:
    branches-ignore:
      - main
      - develop
      - release*
  pull_request:
    branches:
      - main
      - develop
      - release*
  workflow_dispatch:

jobs:
  coverage:

    runs-on: ubuntu-20.04

    name: Generate coverage report
    steps:
    - name: Checkout repostiory
      uses: actions/checkout@v2

    - name: Install python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: x64

    - name: Install dependencies
      run: pip install nox==2020.12.31 poetry==1.1.4

    - name: Run coverage
      run: nox --sessions tests-3.8 coverage
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
